### PR TITLE
opencv 4.10.0

### PR DESCRIPTION
**Pull request by skupr-anaconda**
**Destination channel:** main

### Links

- [PKG-2553](https://anaconda.atlassian.net/browse/PKG-2553) 
- [Upstream repository](https://github.com/opencv/opencv/tree/4.10.0)
- Changelog: https://github.com/opencv/opencv/wiki/ChangeLog#version4100
- License: https://github.com/opencv/opencv/blob/4.10.0/LICENSE
- Requirements:
  - https://github.com/opencv/opencv/blob/4.10.0/CMakeLists.txt
  - https://github.com/opencv/opencv/blob/4.10.0/modules/python/package/setup.py
  - https://github.com/opencv/opencv-python/blob/master/README.md#frequently-asked-questions
  - configs https://github.com/opencv/opencv/blob/4.10.0/doc/tutorials/introduction/config_reference/config_reference.markdown#png-jpeg-tiff-webp-support
  - Windows https://github.com/opencv/opencv/blob/4.10.0/doc/tutorials/introduction/windows_install/windows_install.markdown

### Explanation of changes:

- [x] update to **v4.10.0** (released on _June 3, 2024_, see https://github.com/opencv/opencv/wiki/ChangeLog#version4100)
- [x] Refresh the recipe from conda-forge:
  - [x] update `CMakeLists.txt` for tests
  - [x] set the variables `PKG_CONFIG_PATH` and `PKG_CONFIG_EXECUTABLE` for `FFMPEG`
  - [x] rely on the `C++17` standard
  - [x] add new patches
- [x] set different paths for _Cmake_ and `Python` on Unix and Windows to resolve an old issue of not working `import cv2` for `py-opencv`
  - [ ] fix `py-opencv`'s `import cv2` on `win64` by using `-DCMAKE_FIND_ROOT_PATH=%PREFIX%;%BUILD_PREFIX%`
- [x] resolve the issue of using jasper/openjpeg on different platforms. See [here](https://github.com/opencv/opencv/blob/4.10.0/doc/tutorials/introduction/config_reference/config_reference.markdown#png-jpeg-tiff-webp-support)
  - [x] enable/disable **Jasper 4.2.4** on corresponding platforms correctly.
- [x] Fix souce/url extension as `.tar.gz` instead of `.zip`
- [x] Add `7zip` to a generic `host` on `win` because it's needed for downloading 3rd-party libraries
- [x] Update `host` and `run` pinnings
- [x] Add `libabseil 20240116.2` to support `protobuf >=22` and `c++17` building `dnn` module, see https://github.com/opencv/opencv/issues/24369
- [x] Remove a generic `run` section as redundant 
- [x] Add `libprotobuf 4.25.3`
- [x] Update **opencv** tests:
  - [x] Check if `%LIBRARY_PREFIX%\cmake\x64\vc16\lib\OpenCVModules.cmake` exists on `win`
  - [x] test more opencv libraries in `opencv_libs`, see the [conda-forge list](https://github.com/conda-forge/opencv-feedstock/blob/main/recipe/meta.yaml#L154-L205):
    - [x] osx-arm64 
    - [x] osx-64 
    - [x] linux-64
    - [x] linux-aarch64
    - [x] win-64
- [x] Add `python` to host and run for the `libopencv` and `py-opencv` outputs to build all python variants. Also, adding `numpy` for `py-opencv`
- [x] Use `blas=*=openblas    # [(linux or osx) and x86_64]` in `host` and `run` because `py-opencv`'s host environment tries to pick up **mkl** variant by default and then fails on `osx-64` and `linux-64`.
- [x] Add **py-opencv** tests:
  - [x] test new image files by `run_py_test.py`
  - [x] Fix `- test $(pip list | grep opencv-python | wc -l) -eq 2  # [unix]` by using `-eq 1` because we build a _headless_ variant separately
  - [x] `pip check` and `pip list `commands

#### **TODO**:   

- [ ] Check **runtime** _dependencies_ and _pinnings_ here https://staging.continuum.io/prefect/fs/opencv-feedstock/pr29/1d646cb
- [ ]  enable FFMPEG, see a new PR https://github.com/AnacondaRecipes/ffmpeg-feedstock/pull/5
- [ ] try to build the package without `MacOSX12.3.sdk` in a local `cbc.yaml` on `osx-arm64` on **Prefect** (it was needed for local builds only)

[PKG-2553]: https://anaconda.atlassian.net/browse/PKG-2553?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by skupr-anaconda** [comment]
An error on `linux-aarch64`:
```
CMake Warning at cmake/OpenCVUtils.cmake:785 (message):

  Option WITH_JASPER is enabled but corresponding dependency have not been

  found: "HAVE_JASPER" is FALSE

Call Stack (most recent call first):
  CMakeLists.txt:1908 (ocv_verify_config)
```

**Comment by skupr-anaconda** [comment]
An error on `linux-64` (and the same issue on `win-64`):
```
CMake Warning at cmake/OpenCVUtils.cmake:785 (message):

  Option WITH_PROTOBUF is enabled but corresponding dependency have not been

  found: "HAVE_PROTOBUF" is FALSE

Call Stack (most recent call first):
  CMakeLists.txt:1908 (ocv_verify_config)
```

**Comment by skupr-anaconda** [comment]
The `opencv` subpackage's tests failed  on `win64`:
```
CMake Error at CMakeLists.txt:6 (find_package):

  By not providing "FindOpenCV.cmake" in CMAKE_MODULE_PATH this project has

  asked CMake to find a package configuration file provided by "OpenCV", but

  CMake did not find one.
```

**Comment by skupr-anaconda** [comment]
An error happens only on `osx-64`:
```
└─ opencv 4.9.0.*  is not installable because it requires
       └─ blas * openblas, which conflicts with any installable versions previously reported.
```

UPD. The same is on `linux-64`

**Comment by skupr-anaconda** [comment]
The current blocking `py-opencv`'s error on `win-64` is:
```
Traceback (most recent call last):
  File "C:\b\abs_56bg4h36ti\croot\opencv-suite_1717753038976\test_tmp\run_test.py", line 2, in <module>

    import cv2

ImportError: DLL load failed while importing cv2: The specified module could not be found.
```

**Comment by JeanChristopheMorinPerso** [comment]
@skupr-anaconda Can this PR be closed in favor of #31 ?

**Comment by skupr-anaconda** [comment]
> @skupr-anaconda Can this PR be closed in favor of #31 ?

Yes.

**Pull request closed without merging**
